### ISSUE TITLE
No module named 'sctx.snvs.snvcmp'

### ISSUE THREAD

**Issue by DLuong79** [GWW/sctx#1]
I'm trying to get sctx running on my scnv annotated data, but the module import isn't working. Strangely enough, 'import sctx' doesn't give any errors. This is the code I'm using, from the example:
```
import os, sys
import pandas as pd
from sctx.snvs.snvcmp import GroupBuilder, SampleData
import sctx.genotype as GT
import sctx.refine as RT
from sctx.find_snvs import FindSNVs
```

And this is the error:
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 3
      1 import os, sys
      2 import pandas as pd
----> 3 from sctx.snvs.snvcmp import GroupBuilder, SampleData
      4 import sctx.genotype as GT
      5 import sctx.refine as RT

ModuleNotFoundError: No module named 'sctx.snvs.snvcmp'
```

It's worth noting that during the installation of sctx, this particular line was highlighted in red:
```
zip_safe flag not set; analyzing archive contents...
sctx.snvs.__pycache__.calc.cpython-310: module references __file__
```

**Comment by GWW** [comment]
Hi,

It's strange that you are getting that error.  Perhaps there was an issue with the package installation.  It may be the outdated package installation script I was using.  I have updated the repository.  Could you clone it again and install it using the new instructions in the README?

**Comment by DLuong79** [comment]
When I tried running `sudo pip install .` , I got this error:
```
Processing /data/sctx
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Compiling src/sctx/snvs/calc.pyx because it depends on /tmp/pip-build-env-540s0wg5/overlay/local/lib/python3.10/dist-packages/Cython/Includes/libcpp/__init__.pxd.
      [1/1] Cythonizing src/sctx/snvs/calc.pyx
      running egg_info
      writing sctx.egg-info/PKG-INFO
      writing dependency_links to sctx.egg-info/dependency_links.txt
      writing top-level names to sctx.egg-info/top_level.txt
      error: package directory 'sctx' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by GWW** [comment]
Sorry that's my fault.  I think it's fixed now if you reclone it.

**Comment by DLuong79** [comment]
Running `sudo pip install .` when inside the sctx folder:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by GWW** [comment]
Looks like you are missing the package needed to install python packages with pip:

```
pip install setuptools
```

**Comment by DLuong79** [comment]
Setuptools is already installed with pip. I've been trying to troubleshoot things on my end, but nothing seems to be working.

**Comment by GWW** [comment]
Are you using multiple versions of python or some kind of environment like conda?   I have python in a micromamba instance and when I run my commands I get:

```
gww@GWW:~$ which python
/home/gww/micromamba/envs/GWW/bin/python
gww@GWW:~$ which pip
/home/gww/micromamba/envs/GWW/bin/pip
gww@GWW:~$ python
Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>>
```

**Comment by DLuong79** [comment]
Setuptools is functional and can be imported with no problems, it's just not working for this one specific case. In the conda env:
```
(myenv) dluong@davidsctx:/data/sctx$ which python
/home/dluong/anaconda3/envs/myenv/bin/python
(myenv) dluong@davidsctx:/data/sctx$ which pip
/home/dluong/anaconda3/envs/myenv/bin/pip
(myenv) dluong@davidsctx:/data/sctx$ python
Python 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> 
```
Outside the conda env:
```
dluong@davidsctx:/data/sctx$ which python
/usr/bin/python
dluong@davidsctx:/data/sctx$ which pip
/usr/local/bin/pip
dluong@davidsctx:/data/sctx$ python
Python 3.12.1 (main, Dec 10 2023, 15:07:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> 
```

**Comment by GWW** [comment]
You could try:

`/home/dluong/anaconda3/envs/myenv/bin/pip install .` 

to force the use of your conda pip command.

**Comment by DLuong79** [comment]
I found this answer on StackOverflow and it seems to have worked! https://stackoverflow.com/a/65787633

> For others with the same issue due to a different reason: This can also happen when there's a pyproject.toml in the same directory as the setup.py, even when setuptools is available.
> 
> Removing pyproject.toml fixed the issue for me.
